spring:
  application:
    name: tablereservation
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/PosTechFiap}
      database: PosTechFiap
  mail:
    host: smtp.gmail.com
    port: 587
    username: postechfiap910@gmail.com
    password: yefy ztpi kblc mpfq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  servlet:
    contextPath: "/tableReservation/api"
reservation:
  email-noreply: "postechfiap910@gmail.com"
  spring:
    freemarker:
      check-template-location: false